namespace Game.Presentation.Pure
{
    public enum PartModel
    {
        None,
        FloorTile,
        WallPanel,
        Chest,
        CoinStack,
        Staircase,
        Foundation,
        Pillar,
        Candle,
        Column,
        TorchLit,
        BarrelLarge,
        CratesStacked,
        SwordShield,
        Knight,
        Barbarian,
        SkeletonMinion,
        SkeletonRogue,
        SkeletonWarrior,
        SkeletonMage,
        Sword1Handed,
        Axe2Handed,
        Staff,
        Sword2Handed,
        SwordA,
        AxeB,
        StaffA,
        StaffB,
        BowA
    }
}
