namespace Game.Presentation.Pure
{
    public enum PartModel
    {
        None,
        FloorTile,
        WallPanel,
        Chest,
        CoinStack,
        Staircase,
        Foundation,
        Pillar,
        Candle,
        Column,
        TorchLit,
        BarrelLarge,
        CratesStacked,
        SwordShield,
        Knight,
        Barbarian,
        Rogue,
        Mage,
        SkeletonMinion,
        SkeletonRogue,
        SkeletonWarrior,
        SkeletonMage,
        SwordA,
        AxeB,
        StaffB,
        BowA
    }
}
